name: battery-prediction-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pip:
    - numpy==1.24.3
    - pandas==2.0.3
    - scikit-learn==1.3.0
    - xgboost==1.7.6
    - lightgbm==4.0.0
    - joblib==1.3.1
    - azureml-defaults==1.51.0
    - inference-schema==1.5.0
